# Generated by Django 2.0.8 on 2018-09-14 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebBoard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='board',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Board',
        ),
    ]
