# Generated by Django 2.0.8 on 2018-09-25 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebBoard', '0003_replypost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
