# Generated by Django 2.0.8 on 2018-10-05 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebBoard', '0007_auto_20181005_0643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='hobbies',
        ),
    ]
