# Generated by Django 2.0.8 on 2018-10-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebBoard', '0009_auto_20181005_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hobbies',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
