# Generated by Django 2.0.8 on 2018-10-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebBoard', '0012_auto_20181005_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tag',
            field=models.CharField(choices=[('Django', '1'), ('Java', '2'), ('Python', '3')], max_length=10, null=True),
        ),
    ]
